/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class CompositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Composition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCompositionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCompositionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAuthorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAuthorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_4_1_0 = (RuleCall)cAuthorAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInstrumentKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInstrumentAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInstrumentEStringParserRuleCall_5_1_0 = (RuleCall)cInstrumentAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTonalityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTonalityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTonalityEStringParserRuleCall_6_1_0 = (RuleCall)cTonalityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSoundTempoKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSoundTempoAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSoundTempoEIntParserRuleCall_7_1_0 = (RuleCall)cSoundTempoAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cBracketAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final RuleCall cBracketBracketParserRuleCall_8_0_0 = (RuleCall)cBracketAssignment_8_0.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Keyword cCommaKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cBracketAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final RuleCall cBracketBracketParserRuleCall_8_1_1_0 = (RuleCall)cBracketAssignment_8_1_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cStaffAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final RuleCall cStaffStaffParserRuleCall_9_0_0 = (RuleCall)cStaffAssignment_9_0.eContents().get(0);
		private final Group cGroup_9_1 = (Group)cGroup_9.eContents().get(1);
		private final Keyword cCommaKeyword_9_1_0 = (Keyword)cGroup_9_1.eContents().get(0);
		private final Assignment cStaffAssignment_9_1_1 = (Assignment)cGroup_9_1.eContents().get(1);
		private final RuleCall cStaffStaffParserRuleCall_9_1_1_0 = (RuleCall)cStaffAssignment_9_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Composition:
		//	{Composition}
		//	'Composition'
		//	'[' ('name:' name=EString)? ('author:' author=EString)? ('instrument:' instrument=EString)? ('tonality:'
		//	tonality=EString)? ('soundTempo:' soundTempo=EInt)? (bracket+=Bracket ("," bracket+=Bracket)*)? (staff+=Staff (","
		//	staff+=Staff)*)?
		//	']';
		@Override public ParserRule getRule() { return rule; }
		
		//{Composition} 'Composition' '[' ('name:' name=EString)? ('author:' author=EString)? ('instrument:' instrument=EString)?
		//('tonality:' tonality=EString)? ('soundTempo:' soundTempo=EInt)? (bracket+=Bracket ("," bracket+=Bracket)*)?
		//(staff+=Staff ("," staff+=Staff)*)? ']'
		public Group getGroup() { return cGroup; }
		
		//{Composition}
		public Action getCompositionAction_0() { return cCompositionAction_0; }
		
		//'Composition'
		public Keyword getCompositionKeyword_1() { return cCompositionKeyword_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }
		
		//('name:' name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name:'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//('author:' author=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'author:'
		public Keyword getAuthorKeyword_4_0() { return cAuthorKeyword_4_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_4_1() { return cAuthorAssignment_4_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_4_1_0() { return cAuthorEStringParserRuleCall_4_1_0; }
		
		//('instrument:' instrument=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'instrument:'
		public Keyword getInstrumentKeyword_5_0() { return cInstrumentKeyword_5_0; }
		
		//instrument=EString
		public Assignment getInstrumentAssignment_5_1() { return cInstrumentAssignment_5_1; }
		
		//EString
		public RuleCall getInstrumentEStringParserRuleCall_5_1_0() { return cInstrumentEStringParserRuleCall_5_1_0; }
		
		//('tonality:' tonality=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'tonality:'
		public Keyword getTonalityKeyword_6_0() { return cTonalityKeyword_6_0; }
		
		//tonality=EString
		public Assignment getTonalityAssignment_6_1() { return cTonalityAssignment_6_1; }
		
		//EString
		public RuleCall getTonalityEStringParserRuleCall_6_1_0() { return cTonalityEStringParserRuleCall_6_1_0; }
		
		//('soundTempo:' soundTempo=EInt)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'soundTempo:'
		public Keyword getSoundTempoKeyword_7_0() { return cSoundTempoKeyword_7_0; }
		
		//soundTempo=EInt
		public Assignment getSoundTempoAssignment_7_1() { return cSoundTempoAssignment_7_1; }
		
		//EInt
		public RuleCall getSoundTempoEIntParserRuleCall_7_1_0() { return cSoundTempoEIntParserRuleCall_7_1_0; }
		
		//(bracket+=Bracket ("," bracket+=Bracket)*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//bracket+=Bracket
		public Assignment getBracketAssignment_8_0() { return cBracketAssignment_8_0; }
		
		//Bracket
		public RuleCall getBracketBracketParserRuleCall_8_0_0() { return cBracketBracketParserRuleCall_8_0_0; }
		
		//("," bracket+=Bracket)*
		public Group getGroup_8_1() { return cGroup_8_1; }
		
		//","
		public Keyword getCommaKeyword_8_1_0() { return cCommaKeyword_8_1_0; }
		
		//bracket+=Bracket
		public Assignment getBracketAssignment_8_1_1() { return cBracketAssignment_8_1_1; }
		
		//Bracket
		public RuleCall getBracketBracketParserRuleCall_8_1_1_0() { return cBracketBracketParserRuleCall_8_1_1_0; }
		
		//(staff+=Staff ("," staff+=Staff)*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//staff+=Staff
		public Assignment getStaffAssignment_9_0() { return cStaffAssignment_9_0; }
		
		//Staff
		public RuleCall getStaffStaffParserRuleCall_9_0_0() { return cStaffStaffParserRuleCall_9_0_0; }
		
		//("," staff+=Staff)*
		public Group getGroup_9_1() { return cGroup_9_1; }
		
		//","
		public Keyword getCommaKeyword_9_1_0() { return cCommaKeyword_9_1_0; }
		
		//staff+=Staff
		public Assignment getStaffAssignment_9_1_1() { return cStaffAssignment_9_1_1; }
		
		//Staff
		public RuleCall getStaffStaffParserRuleCall_9_1_1_0() { return cStaffStaffParserRuleCall_9_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class StaffElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.StaffElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRestParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAccidentalParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRepetitionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNoteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//StaffElement:
		//	Rest | Accidental | Repetition | Note;
		@Override public ParserRule getRule() { return rule; }
		
		//Rest | Accidental | Repetition | Note
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Rest
		public RuleCall getRestParserRuleCall_0() { return cRestParserRuleCall_0; }
		
		//Accidental
		public RuleCall getAccidentalParserRuleCall_1() { return cAccidentalParserRuleCall_1; }
		
		//Repetition
		public RuleCall getRepetitionParserRuleCall_2() { return cRepetitionParserRuleCall_2; }
		
		//Note
		public RuleCall getNoteParserRuleCall_3() { return cNoteParserRuleCall_3; }
	}
	public class BracketElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Bracket");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBracketAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeBracketTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Assignment cStavesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStavesStaffParserRuleCall_3_0 = (RuleCall)cStavesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStavesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStavesStaffParserRuleCall_4_1_0 = (RuleCall)cStavesAssignment_4_1.eContents().get(0);
		
		//Bracket:
		//	{Bracket}
		//	'Bracket' type=BracketType?
		//	staves+=Staff ("," staves+=Staff)*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Bracket} 'Bracket' type=BracketType? staves+=Staff ("," staves+=Staff)*
		public Group getGroup() { return cGroup; }
		
		//{Bracket}
		public Action getBracketAction_0() { return cBracketAction_0; }
		
		//'Bracket'
		public Keyword getBracketKeyword_1() { return cBracketKeyword_1; }
		
		//type=BracketType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//BracketType
		public RuleCall getTypeBracketTypeEnumRuleCall_2_0() { return cTypeBracketTypeEnumRuleCall_2_0; }
		
		//staves+=Staff
		public Assignment getStavesAssignment_3() { return cStavesAssignment_3; }
		
		//Staff
		public RuleCall getStavesStaffParserRuleCall_3_0() { return cStavesStaffParserRuleCall_3_0; }
		
		//("," staves+=Staff)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//staves+=Staff
		public Assignment getStavesAssignment_4_1() { return cStavesAssignment_4_1; }
		
		//Staff
		public RuleCall getStavesStaffParserRuleCall_4_1_0() { return cStavesStaffParserRuleCall_4_1_0; }
	}
	public class StaffElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Staff");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStaffAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStaffKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumberEIntParserRuleCall_2_0 = (RuleCall)cNumberAssignment_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cClefKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cClefAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cClefClefParserRuleCall_5_0 = (RuleCall)cClefAssignment_5.eContents().get(0);
		private final Keyword cTimeSignatureKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTimeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTimeTimeSignatureParserRuleCall_7_0 = (RuleCall)cTimeAssignment_7.eContents().get(0);
		private final Keyword cElementsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cElementsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cElementsStaffElementParserRuleCall_10_0 = (RuleCall)cElementsAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cElementsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cElementsStaffElementParserRuleCall_11_1_0 = (RuleCall)cElementsAssignment_11_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightSquareBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Staff:
		//	{Staff}
		//	'Staff' number=EInt
		//	'['
		//	'Clef:' clef=Clef
		//	'timeSignature:' time=TimeSignature
		//	'elements' '[' elements+=StaffElement ("," elements+=StaffElement)* ']'
		//	']';
		@Override public ParserRule getRule() { return rule; }
		
		//{Staff} 'Staff' number=EInt '[' 'Clef:' clef=Clef 'timeSignature:' time=TimeSignature 'elements' '['
		//elements+=StaffElement ("," elements+=StaffElement)* ']' ']'
		public Group getGroup() { return cGroup; }
		
		//{Staff}
		public Action getStaffAction_0() { return cStaffAction_0; }
		
		//'Staff'
		public Keyword getStaffKeyword_1() { return cStaffKeyword_1; }
		
		//number=EInt
		public Assignment getNumberAssignment_2() { return cNumberAssignment_2; }
		
		//EInt
		public RuleCall getNumberEIntParserRuleCall_2_0() { return cNumberEIntParserRuleCall_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//'Clef:'
		public Keyword getClefKeyword_4() { return cClefKeyword_4; }
		
		//clef=Clef
		public Assignment getClefAssignment_5() { return cClefAssignment_5; }
		
		//Clef
		public RuleCall getClefClefParserRuleCall_5_0() { return cClefClefParserRuleCall_5_0; }
		
		//'timeSignature:'
		public Keyword getTimeSignatureKeyword_6() { return cTimeSignatureKeyword_6; }
		
		//time=TimeSignature
		public Assignment getTimeAssignment_7() { return cTimeAssignment_7; }
		
		//TimeSignature
		public RuleCall getTimeTimeSignatureParserRuleCall_7_0() { return cTimeTimeSignatureParserRuleCall_7_0; }
		
		//'elements'
		public Keyword getElementsKeyword_8() { return cElementsKeyword_8; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_9() { return cLeftSquareBracketKeyword_9; }
		
		//elements+=StaffElement
		public Assignment getElementsAssignment_10() { return cElementsAssignment_10; }
		
		//StaffElement
		public RuleCall getElementsStaffElementParserRuleCall_10_0() { return cElementsStaffElementParserRuleCall_10_0; }
		
		//("," elements+=StaffElement)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//elements+=StaffElement
		public Assignment getElementsAssignment_11_1() { return cElementsAssignment_11_1; }
		
		//StaffElement
		public RuleCall getElementsStaffElementParserRuleCall_11_1_0() { return cElementsStaffElementParserRuleCall_11_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_12() { return cRightSquareBracketKeyword_12; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_13() { return cRightSquareBracketKeyword_13; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class ClefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Clef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeClefTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		
		//Clef:
		//	{Clef} type=ClefType?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Clef} type=ClefType?
		public Group getGroup() { return cGroup; }
		
		//{Clef}
		public Action getClefAction_0() { return cClefAction_0; }
		
		//type=ClefType?
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//ClefType
		public RuleCall getTypeClefTypeEnumRuleCall_1_0() { return cTypeClefTypeEnumRuleCall_1_0; }
	}
	public class TimeSignatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TimeSignature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBeatKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBeatAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBeatEIntParserRuleCall_1_0 = (RuleCall)cBeatAssignment_1.eContents().get(0);
		private final Keyword cBeatTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBeatTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBeatTypeEIntParserRuleCall_3_0 = (RuleCall)cBeatTypeAssignment_3.eContents().get(0);
		
		//TimeSignature:
		//	'beat' beat=EInt 'beatType' beatType=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'beat' beat=EInt 'beatType' beatType=EInt
		public Group getGroup() { return cGroup; }
		
		//'beat'
		public Keyword getBeatKeyword_0() { return cBeatKeyword_0; }
		
		//beat=EInt
		public Assignment getBeatAssignment_1() { return cBeatAssignment_1; }
		
		//EInt
		public RuleCall getBeatEIntParserRuleCall_1_0() { return cBeatEIntParserRuleCall_1_0; }
		
		//'beatType'
		public Keyword getBeatTypeKeyword_2() { return cBeatTypeKeyword_2; }
		
		//beatType=EInt
		public Assignment getBeatTypeAssignment_3() { return cBeatTypeAssignment_3; }
		
		//EInt
		public RuleCall getBeatTypeEIntParserRuleCall_3_0() { return cBeatTypeEIntParserRuleCall_3_0; }
	}
	public class RestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Rest");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRestAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRestKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeRestTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Rest:
		//	{Rest}
		//	'rest:'
		//	type=RestType?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Rest} 'rest:' type=RestType?
		public Group getGroup() { return cGroup; }
		
		//{Rest}
		public Action getRestAction_0() { return cRestAction_0; }
		
		//'rest:'
		public Keyword getRestKeyword_1() { return cRestKeyword_1; }
		
		//type=RestType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//RestType
		public RuleCall getTypeRestTypeEnumRuleCall_2_0() { return cTypeRestTypeEnumRuleCall_2_0; }
	}
	public class AccidentalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Accidental");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAccidentalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAccidentalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeAccidentalTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Assignment cPositionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPositionEIntParserRuleCall_3_0 = (RuleCall)cPositionAssignment_3.eContents().get(0);
		
		//Accidental:
		//	{Accidental}
		//	'accidental:'
		//	type=AccidentalType?
		//	position=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//{Accidental} 'accidental:' type=AccidentalType? position=EInt
		public Group getGroup() { return cGroup; }
		
		//{Accidental}
		public Action getAccidentalAction_0() { return cAccidentalAction_0; }
		
		//'accidental:'
		public Keyword getAccidentalKeyword_1() { return cAccidentalKeyword_1; }
		
		//type=AccidentalType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//AccidentalType
		public RuleCall getTypeAccidentalTypeEnumRuleCall_2_0() { return cTypeAccidentalTypeEnumRuleCall_2_0; }
		
		//position=EInt
		public Assignment getPositionAssignment_3() { return cPositionAssignment_3; }
		
		//EInt
		public RuleCall getPositionEIntParserRuleCall_3_0() { return cPositionEIntParserRuleCall_3_0; }
	}
	public class RepetitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Repetition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRepetitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRepetitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeRepetitionTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Repetition:
		//	{Repetition}
		//	'repetition:'
		//	type=RepetitionType?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Repetition} 'repetition:' type=RepetitionType?
		public Group getGroup() { return cGroup; }
		
		//{Repetition}
		public Action getRepetitionAction_0() { return cRepetitionAction_0; }
		
		//'repetition:'
		public Keyword getRepetitionKeyword_1() { return cRepetitionKeyword_1; }
		
		//type=RepetitionType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//RepetitionType
		public RuleCall getTypeRepetitionTypeEnumRuleCall_2_0() { return cTypeRepetitionTypeEnumRuleCall_2_0; }
	}
	public class NoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Note");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNoteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNoteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNoteNameEnumRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLyricsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLyricsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLyricsEStringParserRuleCall_3_1_0 = (RuleCall)cLyricsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDurationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDurationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDurationNoteDurationEnumRuleCall_4_1_0 = (RuleCall)cDurationAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPositionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPositionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPositionEIntParserRuleCall_5_1_0 = (RuleCall)cPositionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDynamicKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDynamicAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDynamicEStringParserRuleCall_6_1_0 = (RuleCall)cDynamicAssignment_6_1.eContents().get(0);
		private final Assignment cOrnamentAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOrnamentOrnamentParserRuleCall_7_0 = (RuleCall)cOrnamentAssignment_7.eContents().get(0);
		private final Assignment cAccidentalAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cAccidentalAccidentalParserRuleCall_8_0 = (RuleCall)cAccidentalAssignment_8.eContents().get(0);
		private final Assignment cArticulationAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cArticulationArticulationParserRuleCall_9_0 = (RuleCall)cArticulationAssignment_9.eContents().get(0);
		private final Assignment cFermataAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Keyword cFermataFermataKeyword_10_0 = (Keyword)cFermataAssignment_10.eContents().get(0);
		private final Assignment cDotAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final Keyword cDotDotKeyword_11_0 = (Keyword)cDotAssignment_11.eContents().get(0);
		
		//Note:
		//	{Note}
		//	'note:' name=NoteName ('lyrics:' lyrics=EString)? ('duration:' duration=NoteDuration)? ('position:' position=EInt)?
		//	('dynamic:' dynamic=EString)?
		//	ornament=Ornament?
		//	accidental=Accidental?
		//	articulation=Articulation?
		//	fermata?='fermata'?
		//	dot?='dot'?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Note} 'note:' name=NoteName ('lyrics:' lyrics=EString)? ('duration:' duration=NoteDuration)? ('position:'
		//position=EInt)? ('dynamic:' dynamic=EString)? ornament=Ornament? accidental=Accidental? articulation=Articulation?
		//fermata?='fermata'? dot?='dot'?
		public Group getGroup() { return cGroup; }
		
		//{Note}
		public Action getNoteAction_0() { return cNoteAction_0; }
		
		//'note:'
		public Keyword getNoteKeyword_1() { return cNoteKeyword_1; }
		
		//name=NoteName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NoteName
		public RuleCall getNameNoteNameEnumRuleCall_2_0() { return cNameNoteNameEnumRuleCall_2_0; }
		
		//('lyrics:' lyrics=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'lyrics:'
		public Keyword getLyricsKeyword_3_0() { return cLyricsKeyword_3_0; }
		
		//lyrics=EString
		public Assignment getLyricsAssignment_3_1() { return cLyricsAssignment_3_1; }
		
		//EString
		public RuleCall getLyricsEStringParserRuleCall_3_1_0() { return cLyricsEStringParserRuleCall_3_1_0; }
		
		//('duration:' duration=NoteDuration)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'duration:'
		public Keyword getDurationKeyword_4_0() { return cDurationKeyword_4_0; }
		
		//duration=NoteDuration
		public Assignment getDurationAssignment_4_1() { return cDurationAssignment_4_1; }
		
		//NoteDuration
		public RuleCall getDurationNoteDurationEnumRuleCall_4_1_0() { return cDurationNoteDurationEnumRuleCall_4_1_0; }
		
		//('position:' position=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'position:'
		public Keyword getPositionKeyword_5_0() { return cPositionKeyword_5_0; }
		
		//position=EInt
		public Assignment getPositionAssignment_5_1() { return cPositionAssignment_5_1; }
		
		//EInt
		public RuleCall getPositionEIntParserRuleCall_5_1_0() { return cPositionEIntParserRuleCall_5_1_0; }
		
		//('dynamic:' dynamic=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'dynamic:'
		public Keyword getDynamicKeyword_6_0() { return cDynamicKeyword_6_0; }
		
		//dynamic=EString
		public Assignment getDynamicAssignment_6_1() { return cDynamicAssignment_6_1; }
		
		//EString
		public RuleCall getDynamicEStringParserRuleCall_6_1_0() { return cDynamicEStringParserRuleCall_6_1_0; }
		
		//ornament=Ornament?
		public Assignment getOrnamentAssignment_7() { return cOrnamentAssignment_7; }
		
		//Ornament
		public RuleCall getOrnamentOrnamentParserRuleCall_7_0() { return cOrnamentOrnamentParserRuleCall_7_0; }
		
		//accidental=Accidental?
		public Assignment getAccidentalAssignment_8() { return cAccidentalAssignment_8; }
		
		//Accidental
		public RuleCall getAccidentalAccidentalParserRuleCall_8_0() { return cAccidentalAccidentalParserRuleCall_8_0; }
		
		//articulation=Articulation?
		public Assignment getArticulationAssignment_9() { return cArticulationAssignment_9; }
		
		//Articulation
		public RuleCall getArticulationArticulationParserRuleCall_9_0() { return cArticulationArticulationParserRuleCall_9_0; }
		
		//fermata?='fermata'?
		public Assignment getFermataAssignment_10() { return cFermataAssignment_10; }
		
		//'fermata'
		public Keyword getFermataFermataKeyword_10_0() { return cFermataFermataKeyword_10_0; }
		
		//dot?='dot'?
		public Assignment getDotAssignment_11() { return cDotAssignment_11; }
		
		//'dot'
		public Keyword getDotDotKeyword_11_0() { return cDotDotKeyword_11_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class OrnamentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Ornament");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOrnamentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOrnamentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeOrnamentTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Ornament:
		//	{Ornament}
		//	'ornament:'
		//	type=OrnamentType?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Ornament} 'ornament:' type=OrnamentType?
		public Group getGroup() { return cGroup; }
		
		//{Ornament}
		public Action getOrnamentAction_0() { return cOrnamentAction_0; }
		
		//'ornament:'
		public Keyword getOrnamentKeyword_1() { return cOrnamentKeyword_1; }
		
		//type=OrnamentType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//OrnamentType
		public RuleCall getTypeOrnamentTypeEnumRuleCall_2_0() { return cTypeOrnamentTypeEnumRuleCall_2_0; }
	}
	public class ArticulationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Articulation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArticulationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cArticulationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeArticulationTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Articulation:
		//	{Articulation}
		//	'articulation:'
		//	type=ArticulationType?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Articulation} 'articulation:' type=ArticulationType?
		public Group getGroup() { return cGroup; }
		
		//{Articulation}
		public Action getArticulationAction_0() { return cArticulationAction_0; }
		
		//'articulation:'
		public Keyword getArticulationKeyword_1() { return cArticulationKeyword_1; }
		
		//type=ArticulationType?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//ArticulationType
		public RuleCall getTypeArticulationTypeEnumRuleCall_2_0() { return cTypeArticulationTypeEnumRuleCall_2_0; }
	}
	
	public class BracketTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BracketType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCurlyEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCurlyCurlyKeyword_0_0 = (Keyword)cCurlyEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSquareEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSquareSquareKeyword_1_0 = (Keyword)cSquareEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum BracketType:
		//	curly | square;
		public EnumRule getRule() { return rule; }
		
		//curly | square
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//curly
		public EnumLiteralDeclaration getCurlyEnumLiteralDeclaration_0() { return cCurlyEnumLiteralDeclaration_0; }
		
		//'curly'
		public Keyword getCurlyCurlyKeyword_0_0() { return cCurlyCurlyKeyword_0_0; }
		
		//square
		public EnumLiteralDeclaration getSquareEnumLiteralDeclaration_1() { return cSquareEnumLiteralDeclaration_1; }
		
		//'square'
		public Keyword getSquareSquareKeyword_1_0() { return cSquareSquareKeyword_1_0; }
	}
	public class RestTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RestType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cWholeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cWholeWholeKeyword_0_0 = (Keyword)cWholeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHalfEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHalfHalfKeyword_1_0 = (Keyword)cHalfEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cQuarterEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cQuarterQuarterKeyword_2_0 = (Keyword)cQuarterEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEighthEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEighthEighthKeyword_3_0 = (Keyword)cEighthEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSixteenthEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSixteenthSixteenthKeyword_4_0 = (Keyword)cSixteenthEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cThirtysecondEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cThirtysecondThirtysecondKeyword_5_0 = (Keyword)cThirtysecondEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSixtyfourthEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSixtyfourthSixtyfourthKeyword_6_0 = (Keyword)cSixtyfourthEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum RestType:
		//	whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth;
		public EnumRule getRule() { return rule; }
		
		//whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//whole
		public EnumLiteralDeclaration getWholeEnumLiteralDeclaration_0() { return cWholeEnumLiteralDeclaration_0; }
		
		//'whole'
		public Keyword getWholeWholeKeyword_0_0() { return cWholeWholeKeyword_0_0; }
		
		//half
		public EnumLiteralDeclaration getHalfEnumLiteralDeclaration_1() { return cHalfEnumLiteralDeclaration_1; }
		
		//'half'
		public Keyword getHalfHalfKeyword_1_0() { return cHalfHalfKeyword_1_0; }
		
		//quarter
		public EnumLiteralDeclaration getQuarterEnumLiteralDeclaration_2() { return cQuarterEnumLiteralDeclaration_2; }
		
		//'quarter'
		public Keyword getQuarterQuarterKeyword_2_0() { return cQuarterQuarterKeyword_2_0; }
		
		//eighth
		public EnumLiteralDeclaration getEighthEnumLiteralDeclaration_3() { return cEighthEnumLiteralDeclaration_3; }
		
		//'eighth'
		public Keyword getEighthEighthKeyword_3_0() { return cEighthEighthKeyword_3_0; }
		
		//sixteenth
		public EnumLiteralDeclaration getSixteenthEnumLiteralDeclaration_4() { return cSixteenthEnumLiteralDeclaration_4; }
		
		//'sixteenth'
		public Keyword getSixteenthSixteenthKeyword_4_0() { return cSixteenthSixteenthKeyword_4_0; }
		
		//thirtysecond
		public EnumLiteralDeclaration getThirtysecondEnumLiteralDeclaration_5() { return cThirtysecondEnumLiteralDeclaration_5; }
		
		//'thirtysecond'
		public Keyword getThirtysecondThirtysecondKeyword_5_0() { return cThirtysecondThirtysecondKeyword_5_0; }
		
		//sixtyfourth
		public EnumLiteralDeclaration getSixtyfourthEnumLiteralDeclaration_6() { return cSixtyfourthEnumLiteralDeclaration_6; }
		
		//'sixtyfourth'
		public Keyword getSixtyfourthSixtyfourthKeyword_6_0() { return cSixtyfourthSixtyfourthKeyword_6_0; }
	}
	public class AccidentalTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AccidentalType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSharpEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSharpSharpKeyword_0_0 = (Keyword)cSharpEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFlatEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFlatFlatKeyword_1_0 = (Keyword)cFlatEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNaturalEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNaturalNaturalKeyword_2_0 = (Keyword)cNaturalEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum AccidentalType:
		//	sharp | flat | natural;
		public EnumRule getRule() { return rule; }
		
		//sharp | flat | natural
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//sharp
		public EnumLiteralDeclaration getSharpEnumLiteralDeclaration_0() { return cSharpEnumLiteralDeclaration_0; }
		
		//'sharp'
		public Keyword getSharpSharpKeyword_0_0() { return cSharpSharpKeyword_0_0; }
		
		//flat
		public EnumLiteralDeclaration getFlatEnumLiteralDeclaration_1() { return cFlatEnumLiteralDeclaration_1; }
		
		//'flat'
		public Keyword getFlatFlatKeyword_1_0() { return cFlatFlatKeyword_1_0; }
		
		//natural
		public EnumLiteralDeclaration getNaturalEnumLiteralDeclaration_2() { return cNaturalEnumLiteralDeclaration_2; }
		
		//'natural'
		public Keyword getNaturalNaturalKeyword_2_0() { return cNaturalNaturalKeyword_2_0; }
	}
	public class RepetitionTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RepetitionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLeftEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLeftLeftKeyword_0_0 = (Keyword)cLeftEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRightEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRightRightKeyword_1_0 = (Keyword)cRightEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum RepetitionType:
		//	left | right;
		public EnumRule getRule() { return rule; }
		
		//left | right
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//left
		public EnumLiteralDeclaration getLeftEnumLiteralDeclaration_0() { return cLeftEnumLiteralDeclaration_0; }
		
		//'left'
		public Keyword getLeftLeftKeyword_0_0() { return cLeftLeftKeyword_0_0; }
		
		//right
		public EnumLiteralDeclaration getRightEnumLiteralDeclaration_1() { return cRightEnumLiteralDeclaration_1; }
		
		//'right'
		public Keyword getRightRightKeyword_1_0() { return cRightRightKeyword_1_0; }
	}
	public class NoteNameElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NoteName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCCKeyword_0_0 = (Keyword)cCEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDDKeyword_1_0 = (Keyword)cDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEEKeyword_2_0 = (Keyword)cEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFFKeyword_3_0 = (Keyword)cFEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGGKeyword_4_0 = (Keyword)cGEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cAEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cAAKeyword_5_0 = (Keyword)cAEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cBEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cBBKeyword_6_0 = (Keyword)cBEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum NoteName:
		//	c | d | e | f | g | a | b;
		public EnumRule getRule() { return rule; }
		
		//c | d | e | f | g | a | b
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//c
		public EnumLiteralDeclaration getCEnumLiteralDeclaration_0() { return cCEnumLiteralDeclaration_0; }
		
		//'c'
		public Keyword getCCKeyword_0_0() { return cCCKeyword_0_0; }
		
		//d
		public EnumLiteralDeclaration getDEnumLiteralDeclaration_1() { return cDEnumLiteralDeclaration_1; }
		
		//'d'
		public Keyword getDDKeyword_1_0() { return cDDKeyword_1_0; }
		
		//e
		public EnumLiteralDeclaration getEEnumLiteralDeclaration_2() { return cEEnumLiteralDeclaration_2; }
		
		//'e'
		public Keyword getEEKeyword_2_0() { return cEEKeyword_2_0; }
		
		//f
		public EnumLiteralDeclaration getFEnumLiteralDeclaration_3() { return cFEnumLiteralDeclaration_3; }
		
		//'f'
		public Keyword getFFKeyword_3_0() { return cFFKeyword_3_0; }
		
		//g
		public EnumLiteralDeclaration getGEnumLiteralDeclaration_4() { return cGEnumLiteralDeclaration_4; }
		
		//'g'
		public Keyword getGGKeyword_4_0() { return cGGKeyword_4_0; }
		
		//a
		public EnumLiteralDeclaration getAEnumLiteralDeclaration_5() { return cAEnumLiteralDeclaration_5; }
		
		//'a'
		public Keyword getAAKeyword_5_0() { return cAAKeyword_5_0; }
		
		//b
		public EnumLiteralDeclaration getBEnumLiteralDeclaration_6() { return cBEnumLiteralDeclaration_6; }
		
		//'b'
		public Keyword getBBKeyword_6_0() { return cBBKeyword_6_0; }
	}
	public class NoteDurationElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NoteDuration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cWholeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cWholeWholeKeyword_0_0 = (Keyword)cWholeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHalfEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHalfHalfKeyword_1_0 = (Keyword)cHalfEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cQuarterEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cQuarterQuarterKeyword_2_0 = (Keyword)cQuarterEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEighthEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEighthEighthKeyword_3_0 = (Keyword)cEighthEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSixteenthEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSixteenthSixteenthKeyword_4_0 = (Keyword)cSixteenthEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cThirtysecondEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cThirtysecondThirtysecondKeyword_5_0 = (Keyword)cThirtysecondEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSixtyfourthEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSixtyfourthSixtyfourthKeyword_6_0 = (Keyword)cSixtyfourthEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum NoteDuration:
		//	whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth;
		public EnumRule getRule() { return rule; }
		
		//whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//whole
		public EnumLiteralDeclaration getWholeEnumLiteralDeclaration_0() { return cWholeEnumLiteralDeclaration_0; }
		
		//'whole'
		public Keyword getWholeWholeKeyword_0_0() { return cWholeWholeKeyword_0_0; }
		
		//half
		public EnumLiteralDeclaration getHalfEnumLiteralDeclaration_1() { return cHalfEnumLiteralDeclaration_1; }
		
		//'half'
		public Keyword getHalfHalfKeyword_1_0() { return cHalfHalfKeyword_1_0; }
		
		//quarter
		public EnumLiteralDeclaration getQuarterEnumLiteralDeclaration_2() { return cQuarterEnumLiteralDeclaration_2; }
		
		//'quarter'
		public Keyword getQuarterQuarterKeyword_2_0() { return cQuarterQuarterKeyword_2_0; }
		
		//eighth
		public EnumLiteralDeclaration getEighthEnumLiteralDeclaration_3() { return cEighthEnumLiteralDeclaration_3; }
		
		//'eighth'
		public Keyword getEighthEighthKeyword_3_0() { return cEighthEighthKeyword_3_0; }
		
		//sixteenth
		public EnumLiteralDeclaration getSixteenthEnumLiteralDeclaration_4() { return cSixteenthEnumLiteralDeclaration_4; }
		
		//'sixteenth'
		public Keyword getSixteenthSixteenthKeyword_4_0() { return cSixteenthSixteenthKeyword_4_0; }
		
		//thirtysecond
		public EnumLiteralDeclaration getThirtysecondEnumLiteralDeclaration_5() { return cThirtysecondEnumLiteralDeclaration_5; }
		
		//'thirtysecond'
		public Keyword getThirtysecondThirtysecondKeyword_5_0() { return cThirtysecondThirtysecondKeyword_5_0; }
		
		//sixtyfourth
		public EnumLiteralDeclaration getSixtyfourthEnumLiteralDeclaration_6() { return cSixtyfourthEnumLiteralDeclaration_6; }
		
		//'sixtyfourth'
		public Keyword getSixtyfourthSixtyfourthKeyword_6_0() { return cSixtyfourthSixtyfourthKeyword_6_0; }
	}
	public class OrnamentTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.OrnamentType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSlideEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSlideSlideKeyword_0_0 = (Keyword)cSlideEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGlissandoEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGlissandoGlissandoKeyword_1_0 = (Keyword)cGlissandoEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAciaccaturaEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAciaccaturaAciaccaturaKeyword_2_0 = (Keyword)cAciaccaturaEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAppoggiaturaEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAppoggiaturaAppoggiaturaKeyword_3_0 = (Keyword)cAppoggiaturaEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTurnEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTurnTurnKeyword_4_0 = (Keyword)cTurnEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMordentEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMordentMordentKeyword_5_0 = (Keyword)cMordentEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTrillEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTrillTrillKeyword_6_0 = (Keyword)cTrillEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum OrnamentType:
		//	slide | glissando | aciaccatura | appoggiatura | turn | mordent | trill;
		public EnumRule getRule() { return rule; }
		
		//slide | glissando | aciaccatura | appoggiatura | turn | mordent | trill
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//slide
		public EnumLiteralDeclaration getSlideEnumLiteralDeclaration_0() { return cSlideEnumLiteralDeclaration_0; }
		
		//'slide'
		public Keyword getSlideSlideKeyword_0_0() { return cSlideSlideKeyword_0_0; }
		
		//glissando
		public EnumLiteralDeclaration getGlissandoEnumLiteralDeclaration_1() { return cGlissandoEnumLiteralDeclaration_1; }
		
		//'glissando'
		public Keyword getGlissandoGlissandoKeyword_1_0() { return cGlissandoGlissandoKeyword_1_0; }
		
		//aciaccatura
		public EnumLiteralDeclaration getAciaccaturaEnumLiteralDeclaration_2() { return cAciaccaturaEnumLiteralDeclaration_2; }
		
		//'aciaccatura'
		public Keyword getAciaccaturaAciaccaturaKeyword_2_0() { return cAciaccaturaAciaccaturaKeyword_2_0; }
		
		//appoggiatura
		public EnumLiteralDeclaration getAppoggiaturaEnumLiteralDeclaration_3() { return cAppoggiaturaEnumLiteralDeclaration_3; }
		
		//'appoggiatura'
		public Keyword getAppoggiaturaAppoggiaturaKeyword_3_0() { return cAppoggiaturaAppoggiaturaKeyword_3_0; }
		
		//turn
		public EnumLiteralDeclaration getTurnEnumLiteralDeclaration_4() { return cTurnEnumLiteralDeclaration_4; }
		
		//'turn'
		public Keyword getTurnTurnKeyword_4_0() { return cTurnTurnKeyword_4_0; }
		
		//mordent
		public EnumLiteralDeclaration getMordentEnumLiteralDeclaration_5() { return cMordentEnumLiteralDeclaration_5; }
		
		//'mordent'
		public Keyword getMordentMordentKeyword_5_0() { return cMordentMordentKeyword_5_0; }
		
		//trill
		public EnumLiteralDeclaration getTrillEnumLiteralDeclaration_6() { return cTrillEnumLiteralDeclaration_6; }
		
		//'trill'
		public Keyword getTrillTrillKeyword_6_0() { return cTrillTrillKeyword_6_0; }
	}
	public class ArticulationTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArticulationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDetachedEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDetachedDetachedKeyword_0_0 = (Keyword)cDetachedEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLegatoEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLegatoLegatoKeyword_1_0 = (Keyword)cLegatoEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStaccatoEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStaccatoStaccatoKeyword_2_0 = (Keyword)cStaccatoEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPortatoEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPortatoPortatoKeyword_3_0 = (Keyword)cPortatoEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTenutoEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTenutoTenutoKeyword_4_0 = (Keyword)cTenutoEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMarcatoEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMarcatoMarcatoKeyword_5_0 = (Keyword)cMarcatoEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum ArticulationType:
		//	detached | legato | staccato | portato | tenuto | marcato;
		public EnumRule getRule() { return rule; }
		
		//detached | legato | staccato | portato | tenuto | marcato
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//detached
		public EnumLiteralDeclaration getDetachedEnumLiteralDeclaration_0() { return cDetachedEnumLiteralDeclaration_0; }
		
		//'detached'
		public Keyword getDetachedDetachedKeyword_0_0() { return cDetachedDetachedKeyword_0_0; }
		
		//legato
		public EnumLiteralDeclaration getLegatoEnumLiteralDeclaration_1() { return cLegatoEnumLiteralDeclaration_1; }
		
		//'legato'
		public Keyword getLegatoLegatoKeyword_1_0() { return cLegatoLegatoKeyword_1_0; }
		
		//staccato
		public EnumLiteralDeclaration getStaccatoEnumLiteralDeclaration_2() { return cStaccatoEnumLiteralDeclaration_2; }
		
		//'staccato'
		public Keyword getStaccatoStaccatoKeyword_2_0() { return cStaccatoStaccatoKeyword_2_0; }
		
		//portato
		public EnumLiteralDeclaration getPortatoEnumLiteralDeclaration_3() { return cPortatoEnumLiteralDeclaration_3; }
		
		//'portato'
		public Keyword getPortatoPortatoKeyword_3_0() { return cPortatoPortatoKeyword_3_0; }
		
		//tenuto
		public EnumLiteralDeclaration getTenutoEnumLiteralDeclaration_4() { return cTenutoEnumLiteralDeclaration_4; }
		
		//'tenuto'
		public Keyword getTenutoTenutoKeyword_4_0() { return cTenutoTenutoKeyword_4_0; }
		
		//marcato
		public EnumLiteralDeclaration getMarcatoEnumLiteralDeclaration_5() { return cMarcatoEnumLiteralDeclaration_5; }
		
		//'marcato'
		public Keyword getMarcatoMarcatoKeyword_5_0() { return cMarcatoMarcatoKeyword_5_0; }
	}
	public class ClefTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ClefType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cViolinEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cViolinViolinKeyword_0_0 = (Keyword)cViolinEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBassEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBassBassKeyword_1_0 = (Keyword)cBassEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum ClefType:
		//	violin | bass;
		public EnumRule getRule() { return rule; }
		
		//violin | bass
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//violin
		public EnumLiteralDeclaration getViolinEnumLiteralDeclaration_0() { return cViolinEnumLiteralDeclaration_0; }
		
		//'violin'
		public Keyword getViolinViolinKeyword_0_0() { return cViolinViolinKeyword_0_0; }
		
		//bass
		public EnumLiteralDeclaration getBassEnumLiteralDeclaration_1() { return cBassEnumLiteralDeclaration_1; }
		
		//'bass'
		public Keyword getBassBassKeyword_1_0() { return cBassBassKeyword_1_0; }
	}
	
	private final CompositionElements pComposition;
	private final StaffElementElements pStaffElement;
	private final BracketElements pBracket;
	private final StaffElements pStaff;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final BracketTypeElements eBracketType;
	private final ClefElements pClef;
	private final TimeSignatureElements pTimeSignature;
	private final RestElements pRest;
	private final AccidentalElements pAccidental;
	private final RepetitionElements pRepetition;
	private final NoteElements pNote;
	private final RestTypeElements eRestType;
	private final AccidentalTypeElements eAccidentalType;
	private final RepetitionTypeElements eRepetitionType;
	private final NoteNameElements eNoteName;
	private final NoteDurationElements eNoteDuration;
	private final EBooleanElements pEBoolean;
	private final OrnamentElements pOrnament;
	private final ArticulationElements pArticulation;
	private final OrnamentTypeElements eOrnamentType;
	private final ArticulationTypeElements eArticulationType;
	private final ClefTypeElements eClefType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pComposition = new CompositionElements();
		this.pStaffElement = new StaffElementElements();
		this.pBracket = new BracketElements();
		this.pStaff = new StaffElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.eBracketType = new BracketTypeElements();
		this.pClef = new ClefElements();
		this.pTimeSignature = new TimeSignatureElements();
		this.pRest = new RestElements();
		this.pAccidental = new AccidentalElements();
		this.pRepetition = new RepetitionElements();
		this.pNote = new NoteElements();
		this.eRestType = new RestTypeElements();
		this.eAccidentalType = new AccidentalTypeElements();
		this.eRepetitionType = new RepetitionTypeElements();
		this.eNoteName = new NoteNameElements();
		this.eNoteDuration = new NoteDurationElements();
		this.pEBoolean = new EBooleanElements();
		this.pOrnament = new OrnamentElements();
		this.pArticulation = new ArticulationElements();
		this.eOrnamentType = new OrnamentTypeElements();
		this.eArticulationType = new ArticulationTypeElements();
		this.eClefType = new ClefTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Composition:
	//	{Composition}
	//	'Composition'
	//	'[' ('name:' name=EString)? ('author:' author=EString)? ('instrument:' instrument=EString)? ('tonality:'
	//	tonality=EString)? ('soundTempo:' soundTempo=EInt)? (bracket+=Bracket ("," bracket+=Bracket)*)? (staff+=Staff (","
	//	staff+=Staff)*)?
	//	']';
	public CompositionElements getCompositionAccess() {
		return pComposition;
	}
	
	public ParserRule getCompositionRule() {
		return getCompositionAccess().getRule();
	}
	
	//StaffElement:
	//	Rest | Accidental | Repetition | Note;
	public StaffElementElements getStaffElementAccess() {
		return pStaffElement;
	}
	
	public ParserRule getStaffElementRule() {
		return getStaffElementAccess().getRule();
	}
	
	//Bracket:
	//	{Bracket}
	//	'Bracket' type=BracketType?
	//	staves+=Staff ("," staves+=Staff)*;
	public BracketElements getBracketAccess() {
		return pBracket;
	}
	
	public ParserRule getBracketRule() {
		return getBracketAccess().getRule();
	}
	
	//Staff:
	//	{Staff}
	//	'Staff' number=EInt
	//	'['
	//	'Clef:' clef=Clef
	//	'timeSignature:' time=TimeSignature
	//	'elements' '[' elements+=StaffElement ("," elements+=StaffElement)* ']'
	//	']';
	public StaffElements getStaffAccess() {
		return pStaff;
	}
	
	public ParserRule getStaffRule() {
		return getStaffAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum BracketType:
	//	curly | square;
	public BracketTypeElements getBracketTypeAccess() {
		return eBracketType;
	}
	
	public EnumRule getBracketTypeRule() {
		return getBracketTypeAccess().getRule();
	}
	
	//Clef:
	//	{Clef} type=ClefType?;
	public ClefElements getClefAccess() {
		return pClef;
	}
	
	public ParserRule getClefRule() {
		return getClefAccess().getRule();
	}
	
	//TimeSignature:
	//	'beat' beat=EInt 'beatType' beatType=EInt;
	public TimeSignatureElements getTimeSignatureAccess() {
		return pTimeSignature;
	}
	
	public ParserRule getTimeSignatureRule() {
		return getTimeSignatureAccess().getRule();
	}
	
	//Rest:
	//	{Rest}
	//	'rest:'
	//	type=RestType?;
	public RestElements getRestAccess() {
		return pRest;
	}
	
	public ParserRule getRestRule() {
		return getRestAccess().getRule();
	}
	
	//Accidental:
	//	{Accidental}
	//	'accidental:'
	//	type=AccidentalType?
	//	position=EInt;
	public AccidentalElements getAccidentalAccess() {
		return pAccidental;
	}
	
	public ParserRule getAccidentalRule() {
		return getAccidentalAccess().getRule();
	}
	
	//Repetition:
	//	{Repetition}
	//	'repetition:'
	//	type=RepetitionType?;
	public RepetitionElements getRepetitionAccess() {
		return pRepetition;
	}
	
	public ParserRule getRepetitionRule() {
		return getRepetitionAccess().getRule();
	}
	
	//Note:
	//	{Note}
	//	'note:' name=NoteName ('lyrics:' lyrics=EString)? ('duration:' duration=NoteDuration)? ('position:' position=EInt)?
	//	('dynamic:' dynamic=EString)?
	//	ornament=Ornament?
	//	accidental=Accidental?
	//	articulation=Articulation?
	//	fermata?='fermata'?
	//	dot?='dot'?;
	public NoteElements getNoteAccess() {
		return pNote;
	}
	
	public ParserRule getNoteRule() {
		return getNoteAccess().getRule();
	}
	
	//enum RestType:
	//	whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth;
	public RestTypeElements getRestTypeAccess() {
		return eRestType;
	}
	
	public EnumRule getRestTypeRule() {
		return getRestTypeAccess().getRule();
	}
	
	//enum AccidentalType:
	//	sharp | flat | natural;
	public AccidentalTypeElements getAccidentalTypeAccess() {
		return eAccidentalType;
	}
	
	public EnumRule getAccidentalTypeRule() {
		return getAccidentalTypeAccess().getRule();
	}
	
	//enum RepetitionType:
	//	left | right;
	public RepetitionTypeElements getRepetitionTypeAccess() {
		return eRepetitionType;
	}
	
	public EnumRule getRepetitionTypeRule() {
		return getRepetitionTypeAccess().getRule();
	}
	
	//enum NoteName:
	//	c | d | e | f | g | a | b;
	public NoteNameElements getNoteNameAccess() {
		return eNoteName;
	}
	
	public EnumRule getNoteNameRule() {
		return getNoteNameAccess().getRule();
	}
	
	//enum NoteDuration:
	//	whole | half | quarter | eighth | sixteenth | thirtysecond | sixtyfourth;
	public NoteDurationElements getNoteDurationAccess() {
		return eNoteDuration;
	}
	
	public EnumRule getNoteDurationRule() {
		return getNoteDurationAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Ornament:
	//	{Ornament}
	//	'ornament:'
	//	type=OrnamentType?;
	public OrnamentElements getOrnamentAccess() {
		return pOrnament;
	}
	
	public ParserRule getOrnamentRule() {
		return getOrnamentAccess().getRule();
	}
	
	//Articulation:
	//	{Articulation}
	//	'articulation:'
	//	type=ArticulationType?;
	public ArticulationElements getArticulationAccess() {
		return pArticulation;
	}
	
	public ParserRule getArticulationRule() {
		return getArticulationAccess().getRule();
	}
	
	//enum OrnamentType:
	//	slide | glissando | aciaccatura | appoggiatura | turn | mordent | trill;
	public OrnamentTypeElements getOrnamentTypeAccess() {
		return eOrnamentType;
	}
	
	public EnumRule getOrnamentTypeRule() {
		return getOrnamentTypeAccess().getRule();
	}
	
	//enum ArticulationType:
	//	detached | legato | staccato | portato | tenuto | marcato;
	public ArticulationTypeElements getArticulationTypeAccess() {
		return eArticulationType;
	}
	
	public EnumRule getArticulationTypeRule() {
		return getArticulationTypeAccess().getRule();
	}
	
	//enum ClefType:
	//	violin | bass;
	public ClefTypeElements getClefTypeAccess() {
		return eClefType;
	}
	
	public EnumRule getClefTypeRule() {
		return getClefTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
