/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterables;
import musicSheetDsl.Composition;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.generator.CompositionDsl;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Composition composition = ((Composition[])Conversions.unwrapArray((Iterables.<Composition>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Composition.class)), Composition.class))[0];
    CompositionDsl dsl = new CompositionDsl(composition);
    String _name = composition.getName();
    String _plus = (_name + ".musicxml");
    fsa.generateFile(_plus, dsl.compositionToXml());
  }
}
